apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lens-user
  namespace: default
roleRef:
  kind: Role
  name: lens-user
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Note that you can specify more than one "subject"
  - kind: Group
    name: kjd4717@hkcloud.co.kr
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: kjd4717@hkcloud.co.kr
    apiGroup: rbac.authorization.k8s.io