apiVersion: apps/v1
kind: Deployment
metadata:
  name: palette3-nginx-ingress
  labels:
    app: palette3-nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palette3-nginx-ingress
  template:
    metadata:
      labels:
        app: palette3-nginx-ingress
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: palette3-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: palette3.orange.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-palette3-ui
                port:
                  number: 80