apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orange
  name: palette3-nginx-ingress
  labels:
    app: palette3-nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palette3-nginx-ingress
  template:
    metadata:
      labels:
        app: palette3-nginx-ingress
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: orange
  name: palette3-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: ttalk.orange.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: palette3-ttalk-ui
                port:
                  number: 9999
          - path: /zzz
            pathType: Prefix
            backend:
              service:
                name: palette3-ttalk-biz
                port:
                  number: 9999

    - host: palette3.orange.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: palette3-ui
                port:
                  number: 3003
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: palette3-api
                port:
                  number: 8080
          - path: /auth-api
            pathType: Prefix
            backend:
              service:
                name: palette3-auth
                port:
                  number: 8080
          - path: /chat-api
            pathType: Prefix
            backend:
              service:
                name: palette3-chat
                port:
                  number: 8080
          - path: /phone-api
            pathType: Prefix
            backend:
              service:
                name: palette3-phone
                port:
                  number: 8080
