apiVersion: v1
kind: Service
metadata:
  namespace: orange
  name: palette3-redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palette3-redis
  namespace: orange
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: palette3-redis
  #podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: palette3-redis
  template:
    metadata:
      labels:
        app: palette3-redis
    spec:
      securityContext:
        sysctls:
          - name: kernel.shm_rmid_forced
            value: "0"
          - name: net.core.somaxconn
            value: "10000"
          - name: kernel.msgmax
            value: "65536"
          - name: fs.file-max
            value: "2097152"
          - name: net.ipv4.ip_local_port_range
            value: "1024 65536"
      containers:
        - name: palette3-redis
          image: redis:5.0.3
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          nfs:
            server: 192.168.56.99
            path: /orange/nfs/redis